In [1]:
import torch

# 创建一个形状为 [2, 3, 4] 的三维张量
tensor = torch.rand(2, 3, 4)

print(tensor)
print(tensor.size())  # 输出张量的形状


tensor([[[0.2217, 0.1305, 0.3020, 0.5603],
         [0.4905, 0.4496, 0.0331, 0.2749],
         [0.7431, 0.9326, 0.6310, 0.0940]],

        [[0.9649, 0.8783, 0.1446, 0.9741],
         [0.3930, 0.0588, 0.9950, 0.2822],
         [0.0032, 0.1763, 0.8156, 0.4153]]])
torch.Size([2, 3, 4])


In [2]:
tensor[[0, 1]] = tensor[[1, 0]] 

In [3]:
print(tensor)

tensor([[[0.9649, 0.8783, 0.1446, 0.9741],
         [0.3930, 0.0588, 0.9950, 0.2822],
         [0.0032, 0.1763, 0.8156, 0.4153]],

        [[0.2217, 0.1305, 0.3020, 0.5603],
         [0.4905, 0.4496, 0.0331, 0.2749],
         [0.7431, 0.9326, 0.6310, 0.0940]]])


In [4]:
tensor[0]

tensor([[0.9649, 0.8783, 0.1446, 0.9741],
        [0.3930, 0.0588, 0.9950, 0.2822],
        [0.0032, 0.1763, 0.8156, 0.4153]])

In [5]:
tensor[1]

tensor([[0.2217, 0.1305, 0.3020, 0.5603],
        [0.4905, 0.4496, 0.0331, 0.2749],
        [0.7431, 0.9326, 0.6310, 0.0940]])

In [ ]:
                if index_block == 12:
                    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
                        create_custom_forward(block),
                        hidden_states,
                        encoder_hidden_states[1],
                        temb,
                        image_rotary_emb,
                        **ckpt_kwargs,
                    )
                else:
                    encoder_hidden_states, hidden_states = torch.utils.checkpoint.checkpoint(
                        create_custom_forward(block),
                        hidden_states,
                        encoder_hidden_states[0],
                        temb,
                        image_rotary_emb,
                        **ckpt_kwargs,
                    )
            else:
                if index_block == 12:
                    encoder_hidden_states, hidden_states = block(
                        hidden_states=hidden_states,
                        encoder_hidden_states=encoder_hidden_states[1],
                        temb=temb,
                        image_rotary_emb=image_rotary_emb,
                        joint_attention_kwargs=joint_attention_kwargs,
                    )
                else:
                    encoder_hidden_states, hidden_states = block(
                        hidden_states=hidden_states,
                        encoder_hidden_states=encoder_hidden_states[0],
                        temb=temb,
                        image_rotary_emb=image_rotary_emb,
                        joint_attention_kwargs=joint_attention_kwargs,
                    )